package com.zivkesten.test.data

import java.lang.Exception

data class CaughtException(
    val exception: String,
    val timeStamp: Long,
)




